---
abstract: 'Method to rank potential keywords of text.'
author:
  - 'Jeff Kubina (jeff.kubina@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Categorize-Textrank
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 1.15
  Graph: 0.91
  Graph::Centrality::Pagerank: 1.04
  Log::Log4perl: 1.25
  Text::StemTagPOS: 0.60
version: 0.51
